//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShop.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketItem
    {
        public System.Guid BasketItemID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual BasketItem BasketItem1 { get; set; }
        public virtual BasketItem BasketItem2 { get; set; }
        public virtual Product Product { get; set; }
    }
}
