//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShop.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGiftCard
    {
        public string Id { get; set; }
        public string EGiftCardCode { get; set; }
        public string EGiftCardDescription { get; set; }
        public decimal EGiftCardCurrentValue { get; set; }
        public string TargetEmail { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
    }
}
