//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShop.Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public string Id { get; set; }
        [Required]
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        [Required]
        public decimal ProductPrice { get; set; }
        public string ProductImage { get; set; }
        public decimal ProductDiscount { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public System.DateTimeOffset CreatedAt { get; set; }
        [DisplayName("Product Category")]
        [Required]
        public string productCategory_Id { get; set; }
        public string productSupplier_Id { get; set; }
        public string productType_Id { get; set; }
        public string size_Id { get; set; }
        public string stock_Id { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductSupplier ProductSupplier { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Size Size { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
